[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "idm-cli"
version = "1.3.0"
description = "A lightning-fast, universal command-line download manager"
readme = "README.md"
license = "MIT"
requires-python = ">=3.8"
authors = [
    { name = "Rehan" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Environment :: Console",
]
dependencies = [
    "typer",
    "rich",
    "curl-cffi>=0.7.0",
    "aiofiles",
    "yt-dlp",
    "pyfiglet",
    "questionary",
    "psutil",
    "platformdirs",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "packaging",
    "ruff",
]

[project.urls]
Homepage = "https://github.com/rj41-w2/idm-cli"

[project.scripts]
idm = "idm_cli.ui.cli:app"

[tool.pytest.ini_options]
asyncio_mode = "auto"
